// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IAntDesignCommentOutlined: typeof import('~icons/ant-design/comment-outlined')['default']
    IAntDesignHeartOutlined: typeof import('~icons/ant-design/heart-outlined')['default']
    IAntDesignRetweetOutlined: typeof import('~icons/ant-design/retweet-outlined')['default']
    IAntDesignShareOutlined: typeof import('~icons/ant-design/share-outlined')['default']
    IAntDesignUploadOutlined: typeof import('~icons/ant-design/upload-outlined')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
